#ifndef BASICUTILS_H
#define BASICUTILS_H
    #include <BasicUtils/debugHelpers.h>
    #include <BasicUtils/BasicClassGroupArray.h>
    #include <BasicUtils/BasicClassGroup.h>
    #include <BasicUtils/BasicClassAccessor.h>
    #include <BasicUtils/BasicClassRegistry.h>
    #include <BasicUtils/BasicFileLocation.h>
    #include <BasicUtils/BasicPluginProxy.h>
    #include <BasicUtils/BasicStringTable.h>
    #include <BasicUtils/BasicString.h>
    #include <BasicUtils/BasicRandomNumberGenerator.h>
    #include <BasicUtils/BasicClassFactoryBase.h>
    #include <BasicUtils/BasicClassFactory.h>
    #include <BasicUtils/BasicPluginInfo.h>
    #include <BasicUtils/BasicDynamicClassNodeBase.h>
    #include <BasicUtils/BasicClassAccessorBase.h>
    #include <BasicUtils/BasicPluginManager.h>
    #include <BasicUtils/wrapdll.h>
    #include <BasicUtils/BasicClassGroupFactory.h>
    #include <BasicUtils/BasicException.h>
#endif